name: Tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: git fetch --progress --depth=1 origin ${{ github.base_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --immutable

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Build step
        run: yarn run build:all

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Lint step
        run: yarn run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Tests step
        run: yarn run test:all
