name: Tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --progress --depth=1 origin ${{ github.base_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            core/lib
            template/lib
          key: ${{ runner.os }}-built-files-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn run build:all

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/cache@v3
        with:
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-built-files-
      - uses: actions/checkout@v3
      - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/cache@v3
        with:
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-built-files-
      - uses: actions/checkout@v3
      - run: yarn run test:all
